pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';
const $=id=>document.getElementById(id);
const els={pdfInput:$('pdfInput'),imageInput:$('imageInput'),openPdfBtn:$('openPdfBtn'),emptyOpenBtn:$('emptyOpenBtn'),replacePdfBtn:$('replacePdfBtn'),exportBtn:$('exportBtn'),addTextBtn:$('addTextBtn'),addImageBtn:$('addImageBtn'),pageList:$('pageList'),pageCount:$('pageCount'),emptyState:$('emptyState'),pageStage:$('pageStage'),pdfCanvas:$('pdfCanvas'),overlayLayer:$('overlayLayer'),documentName:$('documentName'),statusText:$('statusText'),pageIndicator:$('pageIndicator'),zoomLabel:$('zoomLabel'),zoomInBtn:$('zoomInBtn'),zoomOutBtn:$('zoomOutBtn'),fitBtn:$('fitBtn'),noSelection:$('noSelection'),textProperties:$('textProperties'),imageProperties:$('imageProperties'),layerActions:$('layerActions'),textContent:$('textContent'),fontSize:$('fontSize'),fontColor:$('fontColor'),fontFamily:$('fontFamily'),boldBtn:$('boldBtn'),italicBtn:$('italicBtn'),alignLeftBtn:$('alignLeftBtn'),alignCenterBtn:$('alignCenterBtn'),alignRightBtn:$('alignRightBtn'),imageOpacity:$('imageOpacity'),opacityValue:$('opacityValue'),imageRadius:$('imageRadius'),radiusValue:$('radiusValue'),replaceImageBtn:$('replaceImageBtn'),duplicateBtn:$('duplicateBtn'),deleteBtn:$('deleteBtn'),undoBtn:$('undoBtn'),redoBtn:$('redoBtn'),toast:$('toast'),busy:$('busy'),busyText:$('busyText'),stageWrap:$('stageWrap')};
let state={pdf:null,bytes:null,name:'',page:1,pages:[],scale:1,baseScale:1.2,selected:null,history:[],future:[],imageMode:'add',pageNumber:{enabled:false,x:42,y:94,w:16,h:3,fontSize:10}};
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function toast(msg){els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),2200)}
function busy(on,text='Working…'){els.busyText.textContent=text;els.busy.classList.toggle('hidden',!on)}
function snapshot(){return JSON.stringify(state.pages)}
function checkpoint(){state.history.push(snapshot());if(state.history.length>60)state.history.shift();state.future=[];historyButtons()}
function historyButtons(){els.undoBtn.disabled=!state.history.length;els.redoBtn.disabled=!state.future.length}
async function undo(){if(!state.history.length)return;state.future.push(snapshot());state.pages=JSON.parse(state.history.pop());state.selected=null;historyButtons();await renderPage()}
async function redo(){if(!state.future.length)return;state.history.push(snapshot());state.pages=JSON.parse(state.future.pop());state.selected=null;historyButtons();await renderPage()}
['openPdfBtn','emptyOpenBtn','replacePdfBtn'].forEach(id=>els[id].onclick=()=>els.pdfInput.click());
els.pdfInput.onchange=async e=>{const file=e.target.files[0];if(!file)return;busy(true,'Opening PDF…');try{const bytes=new Uint8Array(await file.arrayBuffer());const pdf=await pdfjsLib.getDocument({data:bytes.slice()}).promise;state={...state,pdf,bytes,name:file.name,page:1,pages:Array.from({length:pdf.numPages},()=>[]),selected:null,history:[],future:[]};els.documentName.textContent=file.name;els.pageCount.textContent=pdf.numPages;els.emptyState.classList.add('hidden');els.pageStage.classList.remove('hidden');[els.exportBtn,els.addTextBtn,els.addImageBtn,$('pageNumberBtn')].forEach(x=>x.disabled=false);await buildThumbnails();await fitPage();toast('PDF ready to edit')}catch(err){console.error(err);toast('Could not open this PDF')}finally{busy(false);e.target.value=''}};
async function buildThumbnails(){els.pageList.innerHTML='';for(let n=1;n<=state.pdf.numPages;n++){const card=document.createElement('button');card.className='page-thumb'+(n===state.page?' active':'');card.dataset.page=n;const canvas=document.createElement('canvas');const label=document.createElement('span');label.textContent='Page '+n;card.append(canvas,label);card.onclick=async()=>{state.page=n;state.selected=null;await renderPage();highlightThumb()};els.pageList.append(card);const page=await state.pdf.getPage(n);const vp=page.getViewport({scale:.22});canvas.width=vp.width;canvas.height=vp.height;await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise}}
function highlightThumb(){document.querySelectorAll('.page-thumb').forEach(x=>x.classList.toggle('active',+x.dataset.page===state.page))}
async function fitPage(){if(!state.pdf)return;const page=await state.pdf.getPage(state.page);const vp=page.getViewport({scale:1});const available=Math.max(300,els.stageWrap.clientWidth-72);state.scale=Math.min(1.45,available/vp.width);await renderPage()}
async function renderPage(){if(!state.pdf)return;const page=await state.pdf.getPage(state.page);const viewport=page.getViewport({scale:state.baseScale*state.scale});const dpr=Math.min(devicePixelRatio||1,2);els.pdfCanvas.width=Math.floor(viewport.width*dpr);els.pdfCanvas.height=Math.floor(viewport.height*dpr);els.pdfCanvas.style.width=viewport.width+'px';els.pdfCanvas.style.height=viewport.height+'px';els.pageStage.style.width=viewport.width+'px';els.pageStage.style.height=viewport.height+'px';els.overlayLayer.style.width=viewport.width+'px';els.overlayLayer.style.height=viewport.height+'px';const ctx=els.pdfCanvas.getContext('2d');await page.render({canvasContext:ctx,viewport,transform:dpr!==1?[dpr,0,0,dpr,0,0]:null}).promise;renderOverlays();els.zoomLabel.textContent=Math.round(state.scale*100)+'%';els.pageIndicator.textContent=`Page ${state.page} of ${state.pdf.numPages}`;els.statusText.textContent=`${state.pages.flat().length} layer${state.pages.flat().length===1?'':'s'}`;updateProperties()}
function renderOverlays(){els.overlayLayer.innerHTML='';state.pages[state.page-1].forEach(item=>{const el=document.createElement('div');el.className=`element ${item.type}-element${item.id===state.selected?' selected':''}`;el.dataset.id=item.id;Object.assign(el.style,{left:item.x+'%',top:item.y+'%',width:item.w+'%',height:item.h+'%',transform:`rotate(${item.rotation||0}deg)`,opacity:item.opacity??1});if(item.type==='text'){el.textContent=item.text;Object.assign(el.style,{fontSize:`${item.fontSize*state.scale}px`,fontFamily:item.fontFamily,color:item.color,fontWeight:item.bold?'700':'400',fontStyle:item.italic?'italic':'normal',textAlign:item.align||'left'})}else{const img=document.createElement('img');img.src=item.src;img.alt='Placed photo';img.style.borderRadius=(item.radius||0)+'px';el.append(img)}const badge=document.createElement('span');badge.className='rotate-badge';badge.textContent=item.type==='text'?'TEXT':'PHOTO';const handle=document.createElement('span');handle.className='resize-handle';el.append(badge,handle);wireElement(el,item,handle);els.overlayLayer.append(el)});if(state.pageNumber.enabled)renderPageNumberLayer()}
function renderPageNumberLayer(){const item=state.pageNumber,el=document.createElement('div');el.className='element text-element page-number-element';el.dataset.id='__page_number__';el.textContent=`Page ${state.page} of ${state.pdf.numPages}`;Object.assign(el.style,{left:item.x+'%',top:item.y+'%',width:item.w+'%',height:item.h+'%',fontSize:`${item.fontSize*state.scale}px`,textAlign:'center',fontWeight:'700'});el.onpointerdown=e=>{e.preventDefault();document.querySelectorAll('.element').forEach(node=>node.classList.toggle('selected',node===el));const rect=els.overlayLayer.getBoundingClientRect(),start={x:e.clientX,y:e.clientY,ix:item.x,iy:item.y};el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{item.x=Math.max(0,Math.min(100-item.w,start.ix+(ev.clientX-start.x)/rect.width*100));item.y=Math.max(0,Math.min(100-item.h,start.iy+(ev.clientY-start.y)/rect.height*100));el.style.left=item.x+'%';el.style.top=item.y+'%'};el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null;toast('Page number position applied to every page')}};els.overlayLayer.append(el)}
$('pageNumberBtn').onclick=()=>{state.pageNumber.enabled=!state.pageNumber.enabled;$('pageNumberBtn').classList.toggle('active',state.pageNumber.enabled);state.selected=null;renderOverlays();toast(state.pageNumber.enabled?'Drag the page number to any position':'Page numbers removed')};
function wireElement(el,item,handle){el.onpointerdown=e=>{if(e.target===handle)return;e.preventDefault();state.selected=item.id;document.querySelectorAll('.element').forEach(node=>node.classList.toggle('selected',node.dataset.id===item.id));updateProperties();checkpoint();const rect=els.overlayLayer.getBoundingClientRect();const start={x:e.clientX,y:e.clientY,ix:item.x,iy:item.y};el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{const dx=(ev.clientX-start.x)/rect.width*100,dy=(ev.clientY-start.y)/rect.height*100;item.x=Math.max(0,Math.min(100-item.w,start.ix+dx));item.y=Math.max(0,Math.min(100-item.h,start.iy+dy));el.style.left=item.x+'%';el.style.top=item.y+'%'};el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null;updateStatus()};el.onpointercancel=el.onpointerup};handle.onpointerdown=e=>{e.preventDefault();e.stopPropagation();checkpoint();const rect=els.overlayLayer.getBoundingClientRect();const start={x:e.clientX,y:e.clientY,w:item.w,h:item.h};handle.setPointerCapture(e.pointerId);handle.onpointermove=ev=>{item.w=Math.max(3,Math.min(100-item.x,start.w+(ev.clientX-start.x)/rect.width*100));item.h=Math.max(2,Math.min(100-item.y,start.h+(ev.clientY-start.y)/rect.height*100));el.style.width=item.w+'%';el.style.height=item.h+'%'};handle.onpointerup=()=>{handle.onpointermove=null;handle.onpointerup=null};handle.onpointercancel=handle.onpointerup}}
function select(id){state.selected=id;renderOverlays();updateProperties()}
function selectedItem(){return state.pages[state.page-1]?.find(x=>x.id===state.selected)}
function updateProperties(){const item=selectedItem();els.noSelection.classList.toggle('hidden',!!item);els.textProperties.classList.toggle('hidden',!item||item.type!=='text');els.imageProperties.classList.toggle('hidden',!item||item.type!=='image');els.layerActions.classList.toggle('hidden',!item);if(!item)return;if(item.type==='text'){els.textContent.value=item.text;els.fontSize.value=item.fontSize;els.fontColor.value=item.color;els.fontFamily.value=item.fontFamily;els.boldBtn.classList.toggle('active',item.bold);els.italicBtn.classList.toggle('active',item.italic);['Left','Center','Right'].forEach(v=>els['align'+v+'Btn'].classList.toggle('active',item.align===v.toLowerCase()))}else{els.imageOpacity.value=Math.round((item.opacity??1)*100);els.opacityValue.textContent=els.imageOpacity.value+'%';els.imageRadius.value=item.radius||0;els.radiusValue.textContent=(item.radius||0)+' px'}}
function addText(){checkpoint();const item={id:uid(),type:'text',x:18,y:18,w:35,h:9,text:'Type your text',fontSize:24,fontFamily:'Arial',color:'#172033',bold:false,italic:false,align:'left',rotation:0};state.pages[state.page-1].push(item);state.selected=item.id;renderOverlays();updateProperties();updateStatus()}
els.addTextBtn.onclick=addText;els.addImageBtn.onclick=()=>{state.imageMode='add';els.imageInput.click()};els.replaceImageBtn.onclick=()=>{state.imageMode='replace';els.imageInput.click()};
els.imageInput.onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>12*1024*1024){toast('Please choose an image under 12 MB');return}const src=await fileToData(file);insertImage(src,state.imageMode);e.target.value=''};
function fileToData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function insertImage(src,mode='add'){checkpoint();if(mode==='replace'){const item=selectedItem();if(item?.type==='image')item.src=src}else{const item={id:uid(),type:'image',x:22,y:18,w:32,h:24,src,opacity:1,radius:0,rotation:0};state.pages[state.page-1].push(item);state.selected=item.id}renderOverlays();updateProperties();updateStatus()}
document.addEventListener('paste',async e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.target.isContentEditable)return;const image=[...(e.clipboardData?.items||[])].find(item=>item.type.startsWith('image/'));if(!image)return;e.preventDefault();if(!state.pdf){toast('Open a PDF before pasting a screenshot');return}const file=image.getAsFile();if(!file)return;if(file.size>12*1024*1024){toast('The pasted image is larger than 12 MB');return}try{insertImage(await fileToData(file));toast('Screenshot pasted onto this page')}catch{toast('Could not paste this screenshot')}});
function propChange(fn){const item=selectedItem();if(!item)return;checkpoint();fn(item);renderOverlays();updateProperties();updateStatus()}
els.textContent.oninput=()=>{const i=selectedItem();if(i){i.text=els.textContent.value;renderOverlays();updateStatus()}};els.textContent.onfocus=checkpoint;
els.fontSize.onchange=()=>propChange(i=>i.fontSize=Math.max(6,+els.fontSize.value||24));els.fontColor.onchange=()=>propChange(i=>i.color=els.fontColor.value);els.fontFamily.onchange=()=>propChange(i=>i.fontFamily=els.fontFamily.value);els.boldBtn.onclick=()=>propChange(i=>i.bold=!i.bold);els.italicBtn.onclick=()=>propChange(i=>i.italic=!i.italic);['Left','Center','Right'].forEach(v=>els['align'+v+'Btn'].onclick=()=>propChange(i=>i.align=v.toLowerCase()));els.imageOpacity.oninput=()=>{const i=selectedItem();if(i){i.opacity=+els.imageOpacity.value/100;els.opacityValue.textContent=els.imageOpacity.value+'%';renderOverlays()}};els.imageOpacity.onpointerdown=checkpoint;els.imageRadius.oninput=()=>{const i=selectedItem();if(i){i.radius=+els.imageRadius.value;els.radiusValue.textContent=i.radius+' px';renderOverlays()}};els.imageRadius.onpointerdown=checkpoint;
function removeSelected(){const idx=state.pages[state.page-1].findIndex(x=>x.id===state.selected);if(idx<0)return;checkpoint();state.pages[state.page-1].splice(idx,1);state.selected=null;renderOverlays();updateProperties();updateStatus()}
els.deleteBtn.onclick=removeSelected;els.duplicateBtn.onclick=()=>{const i=selectedItem();if(!i)return;checkpoint();const copy={...i,id:uid(),x:Math.min(100-i.w,i.x+3),y:Math.min(100-i.h,i.y+3)};state.pages[state.page-1].push(copy);state.selected=copy.id;renderOverlays();updateProperties();updateStatus()};els.overlayLayer.onclick=e=>{if(e.target===els.overlayLayer){state.selected=null;renderOverlays();updateProperties()}};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;const i=selectedItem();if((e.key==='Delete'||e.key==='Backspace')&&i){e.preventDefault();removeSelected()}if(i&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();checkpoint();const d=e.shiftKey?1:.2;if(e.key==='ArrowLeft')i.x=Math.max(0,i.x-d);if(e.key==='ArrowRight')i.x=Math.min(100-i.w,i.x+d);if(e.key==='ArrowUp')i.y=Math.max(0,i.y-d);if(e.key==='ArrowDown')i.y=Math.min(100-i.h,i.y+d);renderOverlays()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}});
els.undoBtn.onclick=undo;els.redoBtn.onclick=redo;els.zoomInBtn.onclick=async()=>{state.scale=Math.min(2,state.scale+.1);await renderPage()};els.zoomOutBtn.onclick=async()=>{state.scale=Math.max(.35,state.scale-.1);await renderPage()};els.fitBtn.onclick=fitPage;
function updateStatus(){const total=state.pages.flat().length;els.statusText.textContent=`${total} layer${total===1?'':'s'}`}
async function exportPdf(){if(!state.bytes)return;busy(true,'Creating your PDF…');try{const doc=await PDFLib.PDFDocument.load(state.bytes.slice());const pages=doc.getPages(),numberFont=state.pageNumber.enabled?await doc.embedFont(PDFLib.StandardFonts.Helvetica):null;for(let p=0;p<pages.length;p++){const page=pages[p],{width,height}=page.getSize();for(const item of state.pages[p]){const x=item.x/100*width,w=item.w/100*width,h=item.h/100*height,y=height-item.y/100*height-h;if(item.type==='text'){if(/[^\x20-\x7E\n]/.test(item.text)){const png=await rasterText(item,w,h);const image=await doc.embedPng(png);page.drawImage(image,{x,y,width:w,height:h,opacity:item.opacity??1})}else{const font=await doc.embedFont(fontName(item));const size=Math.max(4,item.fontSize/state.baseScale);const lines=wrapText(item.text,font,size,w);let lineY=y+h-size;for(const line of lines){if(lineY<y)break;const tw=font.widthOfTextAtSize(line,size);let tx=x+2;if(item.align==='center')tx=x+(w-tw)/2;if(item.align==='right')tx=x+w-tw-2;page.drawText(line,{x:tx,y:lineY,size,font,color:hexToRgb(item.color),opacity:item.opacity??1});lineY-=size*1.2}}}else{const raw=await fetch(item.src).then(r=>r.arrayBuffer());let img;try{img=item.src.startsWith('data:image/png')?await doc.embedPng(raw):await doc.embedJpg(raw)}catch{const converted=await convertToPng(item.src);img=await doc.embedPng(converted)}page.drawImage(img,{x,y,width:w,height:h,opacity:item.opacity??1})}}if(state.pageNumber.enabled){const label=`Page ${p+1} of ${pages.length}`,size=state.pageNumber.fontSize,boxX=state.pageNumber.x/100*width,boxW=state.pageNumber.w/100*width,tw=numberFont.widthOfTextAtSize(label,size);page.drawText(label,{x:boxX+(boxW-tw)/2,y:height-(state.pageNumber.y/100*height)-(state.pageNumber.h/100*height)+2,size,font:numberFont,color:PDFLib.rgb(.2,.23,.3)})}}const out=await doc.save();const blob=new Blob([out],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.name.replace(/\.pdf$/i,'')+'-edited.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Edited PDF downloaded')}catch(err){console.error(err);toast('Export failed. Please try again.')}finally{busy(false)}}
function fontName(item){if(item.fontFamily==='Courier New')return item.bold?PDFLib.StandardFonts.CourierBold:PDFLib.StandardFonts.Courier;if(item.fontFamily==='Georgia'||item.fontFamily==='Times New Roman')return item.bold?PDFLib.StandardFonts.TimesRomanBold:PDFLib.StandardFonts.TimesRoman;return item.bold?PDFLib.StandardFonts.HelveticaBold:PDFLib.StandardFonts.Helvetica}
function wrapText(text,font,size,maxWidth){const out=[];for(const para of text.split('\n')){let line='';for(const word of para.split(/\s+/)){const test=line?line+' '+word:word;if(font.widthOfTextAtSize(test,size)>maxWidth&&line){out.push(line);line=word}else line=test}out.push(line)}return out}
function hexToRgb(hex){const n=parseInt(hex.slice(1),16);return PDFLib.rgb(((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255)}
function convertToPng(src){return new Promise(resolve=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);c.toBlob(b=>b.arrayBuffer().then(resolve),'image/png')};img.src=src})}
function rasterText(item,w,h){return new Promise(resolve=>{const ratio=2,c=document.createElement('canvas');c.width=Math.max(2,Math.round(w*ratio));c.height=Math.max(2,Math.round(h*ratio));const ctx=c.getContext('2d');const size=Math.max(8,item.fontSize/state.baseScale)*ratio;ctx.fillStyle=item.color;ctx.textBaseline='top';ctx.font=`${item.italic?'italic ':''}${item.bold?'700 ':'400 '}${size}px ${item.fontFamily}, sans-serif`;ctx.textAlign=item.align||'left';const max=c.width-8*ratio;let yy=2*ratio;for(const para of item.text.split('\n')){let line='';for(const word of para.split(/\s+/)){const test=line?line+' '+word:word;if(ctx.measureText(test).width>max&&line){draw(line);line=word}else line=test}draw(line)}function draw(line){let xx=4*ratio;if(item.align==='center')xx=c.width/2;if(item.align==='right')xx=c.width-4*ratio;ctx.fillText(line,xx,yy,max);yy+=size*1.2}c.toBlob(b=>b.arrayBuffer().then(resolve),'image/png')})}
els.exportBtn.onclick=exportPdf;window.addEventListener('resize',()=>{clearTimeout(window.resizeT);window.resizeT=setTimeout(()=>state.pdf&&fitPage(),200)});

function registerWebMcp(){
  const context=document.modelContext;
  if(!context?.registerTool)return;
  const controller=new AbortController();
  const register=tool=>Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});
  register({name:'read_pdf_editor_state',title:'Read PDF editor state',description:'Read the currently opened PDF, active page, page count, and layer count without changing the document.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({document:state.name||null,activePage:state.pdf?state.page:null,pageCount:state.pdf?.numPages||0,layerCount:state.pages.flat().length})});
  register({name:'add_text_layer',title:'Add text layer',description:'Add a text layer to the active PDF page at a specified position. A PDF must already be open.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1},xPercent:{type:'number',minimum:0,maximum:90},yPercent:{type:'number',minimum:0,maximum:95},fontSize:{type:'number',minimum:6,maximum:160}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!state.pdf)throw new Error('Open a PDF before adding text.');if(!input||typeof input.text!=='string'||!input.text.trim())throw new Error('Text is required.');checkpoint();const item={id:uid(),type:'text',x:Number.isFinite(input.xPercent)?input.xPercent:18,y:Number.isFinite(input.yPercent)?input.yPercent:18,w:35,h:9,text:input.text,fontSize:Number.isFinite(input.fontSize)?input.fontSize:24,fontFamily:'Arial',color:'#172033',bold:false,italic:false,align:'left',rotation:0};state.pages[state.page-1].push(item);state.selected=item.id;renderOverlays();updateProperties();updateStatus();return{id:item.id,page:state.page,text:item.text}}});
}
registerWebMcp();

// PDF utility tools: compress, merge and split
const toolTitles={editor:'PDF Canvas Editor',compress:'Compress PDF',merge:'Merge PDFs',split:'Split PDF',create:'Create PDF',ocr:'Scan to Text'};
document.querySelectorAll('.mode-tab').forEach(tab=>tab.onclick=()=>switchTool(tab.dataset.mode));
function switchTool(mode){document.querySelectorAll('.mode-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.mode===mode));document.querySelectorAll('.tool-view').forEach(view=>view.classList.add('hidden'));$(mode+'View').classList.remove('hidden');$('editorTopActions').classList.toggle('hidden',mode!=='editor');els.documentName.textContent=mode==='editor'?(state.name||'Untitled document'):toolTitles[mode]}
function formatBytes(bytes){if(!Number.isFinite(bytes))return '';if(bytes<1024)return bytes+' B';if(bytes<1048576)return(bytes/1024).toFixed(1)+' KB';return(bytes/1048576).toFixed(bytes>10485760?1:2)+' MB'}
function downloadBytes(bytes,name,type='application/pdf'){const blob=new Blob([bytes],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function bindDropZone(button,input,onFiles){button.onclick=()=>input.click();button.ondragover=e=>{e.preventDefault();button.classList.add('dragging')};button.ondragleave=()=>button.classList.remove('dragging');button.ondrop=e=>{e.preventDefault();button.classList.remove('dragging');const files=[...e.dataTransfer.files].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'));if(files.length)onFiles(files)};input.onchange=()=>{const files=[...input.files];if(files.length)onFiles(files);input.value=''}}

let compressFile=null;
bindDropZone($('chooseCompressBtn'),$('compressInput'),files=>setCompressFile(files[0]));
function setCompressFile(file){compressFile=file;$('compressFileChip').classList.remove('hidden');$('compressOptions').classList.remove('hidden');$('compressResult').classList.add('hidden');$('compressFileName').textContent=file.name;$('compressFileSize').textContent=formatBytes(file.size)}
$('clearCompressBtn').onclick=()=>{compressFile=null;$('compressFileChip').classList.add('hidden');$('compressOptions').classList.add('hidden');$('compressResult').classList.add('hidden')};
$('compressBtn').onclick=async()=>{if(!compressFile)return;busy(true,'Compressing PDF pages…');try{const source=new Uint8Array(await compressFile.arrayBuffer());const pdf=await pdfjsLib.getDocument({data:source.slice()}).promise;const out=await PDFLib.PDFDocument.create();const settings={high:{scale:1.65,quality:.86},medium:{scale:1.3,quality:.68},low:{scale:1,quality:.48}}[$('compressionLevel').value];for(let n=1;n<=pdf.numPages;n++){els.busyText.textContent=`Compressing page ${n} of ${pdf.numPages}…`;const page=await pdf.getPage(n),unit=page.getViewport({scale:1}),vp=page.getViewport({scale:settings.scale}),canvas=document.createElement('canvas');canvas.width=Math.round(vp.width);canvas.height=Math.round(vp.height);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:vp,background:'white'}).promise;const jpg=await canvasToBytes(canvas,'image/jpeg',settings.quality),image=await out.embedJpg(jpg),newPage=out.addPage([unit.width,unit.height]);newPage.drawImage(image,{x:0,y:0,width:unit.width,height:unit.height});canvas.width=canvas.height=1}const bytes=await out.save({useObjectStreams:true});downloadBytes(bytes,compressFile.name.replace(/\.pdf$/i,'')+'-compressed.pdf');const change=compressFile.size-bytes.length;$('compressResult').classList.remove('hidden');$('compressSaving').textContent=change>0?`${formatBytes(compressFile.size)} → ${formatBytes(bytes.length)} · ${Math.round(change/compressFile.size*100)}% smaller`:`${formatBytes(bytes.length)} · already optimized`;toast('Compressed PDF downloaded')}catch(err){console.error(err);toast('Could not compress this PDF')}finally{busy(false)}};
function canvasToBytes(canvas,type,quality){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?blob.arrayBuffer().then(resolve):reject(new Error('Image conversion failed')),type,quality))}

let mergeFiles=[];
bindDropZone($('chooseMergeBtn'),$('mergeInput'),files=>{mergeFiles.push(...files);renderMergeList()});
function renderMergeList(){$('mergeList').innerHTML='';mergeFiles.forEach((file,index)=>{const row=document.createElement('div');row.className='merge-row';row.innerHTML=`<span class="merge-index">${index+1}</span><div class="merge-info"><b></b><small>${formatBytes(file.size)}</small></div><div class="merge-actions"><button title="Move up">↑</button><button title="Move down">↓</button><button title="Remove">×</button></div>`;row.querySelector('b').textContent=file.name;const buttons=row.querySelectorAll('button');buttons[0].disabled=index===0;buttons[1].disabled=index===mergeFiles.length-1;buttons[0].onclick=()=>moveMerge(index,-1);buttons[1].onclick=()=>moveMerge(index,1);buttons[2].onclick=()=>{mergeFiles.splice(index,1);renderMergeList()};$('mergeList').append(row)});$('mergeBtn').classList.toggle('hidden',mergeFiles.length<2)}
function moveMerge(index,step){const next=index+step;[mergeFiles[index],mergeFiles[next]]=[mergeFiles[next],mergeFiles[index]];renderMergeList()}
$('mergeBtn').onclick=async()=>{if(mergeFiles.length<2)return;busy(true,'Merging PDFs…');try{const out=await PDFLib.PDFDocument.create();for(let i=0;i<mergeFiles.length;i++){els.busyText.textContent=`Adding file ${i+1} of ${mergeFiles.length}…`;const src=await PDFLib.PDFDocument.load(await mergeFiles[i].arrayBuffer()),pages=await out.copyPages(src,src.getPageIndices());pages.forEach(page=>out.addPage(page))}const bytes=await out.save({useObjectStreams:true});downloadBytes(bytes,'merged-document.pdf');toast(`${mergeFiles.length} PDFs merged and downloaded`)}catch(err){console.error(err);toast('Could not merge one of these PDFs')}finally{busy(false)}};

let splitFile=null,splitPageCount=0,splitSelected=new Set();
bindDropZone($('chooseSplitBtn'),$('splitInput'),files=>setSplitFile(files[0]));
async function setSplitFile(file){busy(true,'Creating page previews…');try{const bytes=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data:bytes.slice()}).promise;splitFile=file;splitPageCount=pdf.numPages;splitSelected=new Set(Array.from({length:splitPageCount},(_,i)=>i));$('splitFileChip').classList.remove('hidden');$('splitOptions').classList.remove('hidden');$('splitFileName').textContent=file.name;$('splitFileMeta').textContent=`${formatBytes(file.size)} · ${splitPageCount} page${splitPageCount===1?'':'s'}`;await renderSplitPreviews(pdf)}catch(err){console.error(err);toast('Could not read this PDF')}finally{busy(false)}}
async function renderSplitPreviews(pdf){const grid=$('splitPreviewGrid');grid.innerHTML='';for(let i=0;i<splitPageCount;i++){els.busyText.textContent=`Creating preview ${i+1} of ${splitPageCount}…`;const card=document.createElement('div');card.className='split-page';card.dataset.page=i;const canvas=document.createElement('canvas'),footer=document.createElement('div');footer.className='split-page-footer';footer.innerHTML=`<span>Page ${i+1}</span><button type="button">Remove</button>`;footer.querySelector('button').onclick=()=>toggleSplitPage(i);card.append(canvas,footer);grid.append(card);const page=await pdf.getPage(i+1),vp=page.getViewport({scale:.28});canvas.width=Math.round(vp.width);canvas.height=Math.round(vp.height);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise}updateSplitSelection()}
function toggleSplitPage(index){splitSelected.has(index)?splitSelected.delete(index):splitSelected.add(index);updateSplitSelection()}
function updateSplitSelection(){document.querySelectorAll('.split-page').forEach(card=>{const kept=splitSelected.has(+card.dataset.page);card.classList.toggle('excluded',!kept);card.querySelector('button').textContent=kept?'Remove':'Restore'});$('splitSelectionCount').textContent=`${splitSelected.size} of ${splitPageCount} pages kept`;$('splitBtn').disabled=!splitSelected.size}
$('keepAllPagesBtn').onclick=()=>{splitSelected=new Set(Array.from({length:splitPageCount},(_,i)=>i));updateSplitSelection()};
$('removeAllPagesBtn').onclick=()=>{splitSelected.clear();updateSplitSelection()};
$('clearSplitBtn').onclick=()=>{splitFile=null;splitPageCount=0;splitSelected.clear();$('splitPreviewGrid').innerHTML='';$('splitFileChip').classList.add('hidden');$('splitOptions').classList.add('hidden')};
$('splitBtn').onclick=async()=>{if(!splitFile||!splitSelected.size)return;busy(true,'Preparing selected pages…');try{const source=await PDFLib.PDFDocument.load(await splitFile.arrayBuffer()),base=splitFile.name.replace(/\.pdf$/i,''),indices=[...splitSelected].sort((a,b)=>a-b);if($('splitMethod').value==='range'){const out=await PDFLib.PDFDocument.create(),pages=await out.copyPages(source,indices);pages.forEach(page=>out.addPage(page));downloadBytes(await out.save({useObjectStreams:true}),base+'-selected-pages.pdf');toast(`${indices.length} kept page${indices.length===1?'':'s'} downloaded`)}else{const zip=new JSZip();for(let pos=0;pos<indices.length;pos++){const i=indices[pos];els.busyText.textContent=`Saving page ${pos+1} of ${indices.length}…`;const out=await PDFLib.PDFDocument.create(),[page]=await out.copyPages(source,[i]);out.addPage(page);zip.file(`${base}-page-${i+1}.pdf`,await out.save({useObjectStreams:true}))}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=base+'-selected-pages.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toast(`${indices.length} kept pages saved as ZIP`)}}catch(err){console.error(err);toast('Could not split this PDF')}finally{busy(false)}};

let createPages=[];
bindDropZone($('chooseCreateBtn'),$('createInput'),files=>addCreateFiles(files));
async function addCreateFiles(files){busy(true,'Preparing files…');let added=0;for(let f=0;f<files.length;f++){const file=files[f],name=file.name.toLowerCase();els.busyText.textContent=`Preparing ${file.name}…`;try{let pages=[];if(name.endsWith('.pdf'))pages=await pagesFromPdf(file);else if(file.type.startsWith('image/')||/\.(png|jpe?g|webp)$/.test(name))pages=[await pageFromImage(file)];else if(name.endsWith('.docx'))pages=await pagesFromDocx(file);else if(/\.(xlsx|xls|csv)$/.test(name))pages=await pagesFromSheet(file);else throw new Error('Unsupported file');createPages.push(...pages);added+=pages.length}catch(err){console.error(err);toast(`Could not convert ${file.name}`)}}renderCreatePages();busy(false);if(added)toast(`${added} page${added===1?'':'s'} added`)}
async function pagesFromPdf(file){const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,out=[];for(let i=1;i<=pdf.numPages;i++){els.busyText.textContent=`Rendering ${file.name} · page ${i}/${pdf.numPages}`;const page=await pdf.getPage(i),vp=page.getViewport({scale:1.35}),canvas=document.createElement('canvas');canvas.width=Math.round(vp.width);canvas.height=Math.round(vp.height);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:vp,background:'white'}).promise;out.push({id:uid(),name:file.name,label:`PDF page ${i}`,src:canvas.toDataURL('image/jpeg',.88)});canvas.width=canvas.height=1}return out}
async function pageFromImage(file){return{id:uid(),name:file.name,label:'Photo',src:await fileToData(file)}}
async function pagesFromDocx(file){const result=await mammoth.convertToHtml({arrayBuffer:await file.arrayBuffer()}),host=$('documentRenderHost');host.innerHTML=result.value||'<p>Empty document</p>';return captureDocumentPages(host,file.name,'Word')}
async function pagesFromSheet(file){const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),out=[],host=$('documentRenderHost');for(const sheetName of workbook.SheetNames){host.innerHTML=`<h2>${escapeHtml(sheetName)}</h2>`+XLSX.utils.sheet_to_html(workbook.Sheets[sheetName]);out.push(...await captureDocumentPages(host,file.name,`Sheet: ${sheetName}`))}return out}
async function captureDocumentPages(host,name,label){await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const full=await html2canvas(host,{backgroundColor:'#ffffff',scale:1,useCORS:true,logging:false}),pageHeight=1123,out=[];for(let y=0,index=1;y<full.height;y+=pageHeight,index++){const c=document.createElement('canvas');c.width=794;c.height=pageHeight;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(full,0,y,full.width,Math.min(pageHeight,full.height-y),0,0,c.width,Math.min(pageHeight,full.height-y));out.push({id:uid(),name,label:`${label} · page ${index}`,src:c.toDataURL('image/jpeg',.9)})}host.innerHTML='';return out}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function renderCreatePages(){$('createPreviewGrid').innerHTML='';createPages.forEach((page,index)=>{const card=document.createElement('div');card.className='create-page';card.innerHTML=`<img alt="Page preview"><div class="create-page-meta"><b></b><span></span></div><div class="create-page-actions"><button title="Move left">←</button><button title="Move right">→</button><button title="Remove">×</button></div>`;card.querySelector('img').src=page.src;card.querySelector('b').textContent=page.name;card.querySelector('.create-page-meta span').textContent=`${index+1}. ${page.label}`;const buttons=card.querySelectorAll('button');buttons[0].disabled=index===0;buttons[1].disabled=index===createPages.length-1;buttons[0].onclick=()=>moveCreatePage(index,-1);buttons[1].onclick=()=>moveCreatePage(index,1);buttons[2].onclick=()=>{createPages.splice(index,1);renderCreatePages()};$('createPreviewGrid').append(card)});$('createHead').classList.toggle('hidden',!createPages.length);$('createFooter').classList.toggle('hidden',!createPages.length);$('createPageCount').textContent=`${createPages.length} page${createPages.length===1?'':'s'}`}
function moveCreatePage(index,step){const next=index+step;[createPages[index],createPages[next]]=[createPages[next],createPages[index]];renderCreatePages()}
$('clearCreateBtn').onclick=()=>{createPages=[];renderCreatePages()};
$('createPdfBtn').onclick=async()=>{if(!createPages.length)return;busy(true,'Creating combined PDF…');try{const doc=await PDFLib.PDFDocument.create(),font=$('createPageNumbers').checked?await doc.embedFont(PDFLib.StandardFonts.Helvetica):null,total=createPages.length;for(let i=0;i<total;i++){els.busyText.textContent=`Creating page ${i+1} of ${total}…`;const item=createPages[i],raw=await fetch(item.src).then(r=>r.arrayBuffer());let image;try{image=item.src.startsWith('data:image/png')?await doc.embedPng(raw):await doc.embedJpg(raw)}catch{image=await doc.embedPng(await convertToPng(item.src))}const page=doc.addPage([595.28,841.89]),availableH=font?790:802,scale=Math.min(555/image.width,availableH/image.height),w=image.width*scale,h=image.height*scale;page.drawImage(image,{x:(595.28-w)/2,y:font?35+(availableH-h)/2:(841.89-h)/2,width:w,height:h});if(font){const label=`Page ${i+1} of ${total}`,size=10,tw=font.widthOfTextAtSize(label,size),boxX=state.pageNumber.x/100*595.28,boxW=state.pageNumber.w/100*595.28,y=841.89-(state.pageNumber.y/100*841.89)-(state.pageNumber.h/100*841.89)+2;page.drawText(label,{x:Math.max(8,Math.min(587-tw,boxX+(boxW-tw)/2)),y:Math.max(8,Math.min(825,y)),size,font,color:PDFLib.rgb(.2,.23,.3)})}}downloadBytes(await doc.save({useObjectStreams:true}),'created-document.pdf');toast('New PDF created and downloaded')}catch(err){console.error(err);toast('Could not create this PDF')}finally{busy(false)}};

let ocrFile=null,ocrPlainText='';
bindDropZone($('chooseOcrBtn'),$('ocrInput'),files=>{ocrFile=files[0];$('ocrOptions').classList.remove('hidden');$('ocrResult').classList.add('hidden');$('chooseOcrBtn').querySelector('b').textContent=ocrFile.name;$('chooseOcrBtn').querySelector('span').textContent=formatBytes(ocrFile.size)});
$('runOcrBtn').onclick=async()=>{if(!ocrFile)return;busy(true,'Preparing OCR…');let worker;try{const sources=[];if(ocrFile.name.toLowerCase().endsWith('.pdf')){const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await ocrFile.arrayBuffer())}).promise;for(let i=1;i<=pdf.numPages;i++){els.busyText.textContent=`Preparing scanned page ${i} of ${pdf.numPages}…`;const page=await pdf.getPage(i),vp=page.getViewport({scale:2}),canvas=document.createElement('canvas');canvas.width=Math.round(vp.width);canvas.height=Math.round(vp.height);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport:vp,background:'white'}).promise;sources.push(canvas)}}else sources.push(ocrFile);worker=await Tesseract.createWorker($('ocrLanguage').value,1,{logger:m=>{if(m.status==='recognizing text')els.busyText.textContent=`Recognizing text · ${Math.round((m.progress||0)*100)}%`}});let html='',plain='';for(let i=0;i<sources.length;i++){els.busyText.textContent=`Reading page ${i+1} of ${sources.length}…`;const result=await worker.recognize(sources[i],{}, {text:true,tsv:true,blocks:true});plain+=(i?'\n\n--- Page '+(i+1)+' ---\n\n':'')+(result.data.text||'');html+=buildOcrPage(result.data,i+1);if(sources[i] instanceof HTMLCanvasElement)sources[i].width=sources[i].height=1}ocrPlainText=plain.trim();$('ocrText').innerHTML=$('ocrLayout').value==='plain'?plainToHtml(ocrPlainText):html;$('ocrResult').classList.remove('hidden');$('ocrStats').textContent=`${sources.length} page${sources.length===1?'':'s'} · ${ocrPlainText.length.toLocaleString()} characters`;toast('Formatted text is ready')}catch(err){console.error(err);toast('OCR could not read this file')}finally{if(worker)await worker.terminate();busy(false)}};
function buildOcrPage(data,pageNumber){const lines=parseOcrLines(data.tsv||''),maxX=Math.max(1,...lines.map(l=>l.left+l.width)),left=[],right=[];for(const line of lines)(line.left<maxX*.48?left:right).push(line);const render=items=>items.sort((a,b)=>a.top-b.top).map(x=>`<p>${escapeHtml(x.text)}</p>`).join('');return`<section class="ocr-page"><h3>Page ${pageNumber}</h3><div class="ocr-columns"><div class="ocr-column">${render(left)}</div><div class="ocr-column">${render(right)}</div></div></section>`}
function parseOcrLines(tsv){const rows=tsv.trim().split('\n').slice(1).map(r=>r.split('\t')).filter(c=>c.length>=12&&c[0]==='5'&&c[11]?.trim()),groups=new Map();for(const c of rows){const key=`${c[2]}-${c[3]}-${c[4]}`,word={left:+c[6],top:+c[7],width:+c[8],height:+c[9],text:c[11]};if(!groups.has(key))groups.set(key,[]);groups.get(key).push(word)}return[...groups.values()].map(words=>({left:Math.min(...words.map(w=>w.left)),top:Math.min(...words.map(w=>w.top)),width:Math.max(...words.map(w=>w.left+w.width))-Math.min(...words.map(w=>w.left)),text:words.sort((a,b)=>a.left-b.left).map(w=>w.text).join(' ')}))}
function plainToHtml(text){return`<section class="ocr-page"><div class="ocr-column">${text.split('\n').map(line=>`<p>${escapeHtml(line)||'&nbsp;'}</p>`).join('')}</div></section>`}
function currentOcrText(){return $('ocrText').innerText.trim()}
$('copyOcrBtn').onclick=async()=>{await navigator.clipboard.writeText(currentOcrText());toast('Text copied')};
$('downloadOcrBtn').onclick=()=>downloadTextFile(currentOcrText(),'.txt','text/plain;charset=utf-8');
$('downloadOcrWordBtn').onclick=()=>{const html=`<html><head><meta charset="utf-8"><style>body{font-family:Arial,'Myanmar Text',sans-serif;line-height:1.6;padding:30px}.ocr-columns{display:table;width:100%;table-layout:fixed}.ocr-column{display:table-cell;width:50%;padding:0 16px;vertical-align:top}p{margin:0 0 8px}.ocr-page{page-break-after:always}</style></head><body>${$('ocrText').innerHTML}</body></html>`;downloadTextFile(html,'.doc','application/msword')};
$('downloadOcrPdfBtn').onclick=async()=>{busy(true,'Creating clean PDF…');try{const host=$('documentRenderHost');host.innerHTML=$('ocrText').innerHTML;const pages=await captureDocumentPages(host,'OCR document','OCR');const doc=await PDFLib.PDFDocument.create();for(const item of pages){const raw=await fetch(item.src).then(r=>r.arrayBuffer()),img=await doc.embedJpg(raw),page=doc.addPage([595.28,841.89]);page.drawImage(img,{x:0,y:0,width:595.28,height:841.89})}downloadBytes(await doc.save({useObjectStreams:true}),(ocrFile?.name.replace(/\.[^.]+$/,'')||'scanned')+'-formatted.pdf');toast('Formatted PDF downloaded')}catch(err){console.error(err);toast('Could not create PDF')}finally{busy(false)}};
function downloadTextFile(content,ext,type){const blob=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(ocrFile?.name.replace(/\.[^.]+$/,'')||'scanned')+'-formatted'+ext;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
